### ISSUE TITLE
Incorrect translation of array of structs

### ISSUE THREAD

**Issue by bachmeil** [dkorpel/ctod#36] opened 2024-01-08 22:42 UTC
str.c

```
struct S { double x; int y; }
Sarray[2] = {
	{1.5, 2},
	{2.5, 3}
}
```

That produces

```
module str;
@nogc nothrow:
extern(C): __gshared:
struct S { double x = 0; int y; }S[2] Sarray = [
	[1.5, 2],
	[2.5, 3]
];
```

Which results in the error

```
str.d(5): Error: cannot implicitly convert expression `[1.5, 2.0]` of type `double[]` to `S`
str.d(6): Error: cannot implicitly convert expression `[2.5, 3.0]` of type `double[]` to `S`
```

The fix is simple, it should instead generate

```
struct S { double x = 0; int y; }S[2] Sarray = [
	{1.5, 2},
	{2.5, 3}
];
```

**Comment by dkorpel** [comment] 2024-01-08 23:15
The problem is that initializer lists with `{ }` are generic in C, used for both structs and arrays, while in D you have to choose between `[ ]` and `{ }` based on the type. Currently ctod just guesses and sees Sarray is an array, so it just replaces all `{ }` with `[ ]`. 

Since in this case the exact array type is known, it can be improved.

**Comment by dkorpel** [comment] 2024-01-30 10:09
Fixed by https://github.com/dkorpel/ctod/commit/e452d3bdc159ed7802c4e910bfdc1db134a6f628

I know there's still more cases it would get wrong, but I'll defer implementing full initializer semantic for now. Feel free to open new issues with new cases.

**Closed by dkorpel** 2024-01-30 10:09 UTC
